sudo: required 

services: 
    - docker 

before_install:
    - docker build -t aditya044/docker-react -f Dockerfile.dev .

script:
    - docker run aditya044/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
region: "us-east-2"
app: "docker"
env: "Docker-env"
bucket_name: "elasticbeanstalk-us-east-2-985786338562"
bucket_path: "docker"
on:
  branch: master

access_key_id: "$AWS_ACCESS_KEY"
secret-access-key:
    secure: "$AWS_SECRET_KEY"

